version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: clarbank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/Script-1.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: clarbank-backend
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: Front/Dockerfile
      args:
        # Para entorno local: el navegador accede a http://localhost:3000
        VITE_API_BASE: http://localhost:3000
    container_name: clarbank-front
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:

